export const skills = [
  { name: "React", icon: "⚛️" },
  { name: "TypeScript", icon: "🟦" },
  { name: "Tailwind CSS", icon: "🌊" },
  { name: "Next.js", icon: "▲" },
  { name: "JavaScript", icon: "🟨" },
  { name: "CSS", icon: "🎨" },
  { name: "Claude", icon: "🤖" },
  { name: "Codex", icon: "📜" },
  { name: "Cursor", icon: "🖱️" },
  { name: "Antigravity", icon: "🛸" },
  { name: "CI/CD", icon: "♾️" },
  { name: "Git", icon: "🐙" },
  { name: "REST APIs", icon: "🔄" },
  { name: "Vite", icon: "📦" },
  { name: "Testing", icon: "🧪" },
  { name: "Framer Motion", icon: "🎭" },
  { name: "Zustand/Redux", icon: "🗄️" },
  { name: "PostgreSQL", icon: "🐘" },
  { name: "Docker", icon: "🐋" },
  { name: "Redis", icon: "🔴" },
  { name: "HTML", icon: "🧡" },
  { name: "MongoDB", icon: "🍃" },
  { name: "Figma", icon: "🎨" },
  { name: "Magento", icon: "🛍️" },
];

export const projects = [
  {
    title: "TrueForm",
    description:
      "A SaaS platform unifying forms, bookings, payments, and e-signatures for service businesses.",
    bullets: [
      "Drag-and-drop form builder with 15+ field types, real-time canvas previews, and a 6-step multi-step renderer with per-step validation",
      "In-browser eSignature canvas, OTP verification flow, and Paymob-styled payment UI with live formatting and multi-method tabs",
      "Full admin dashboard with live submission filtering, slide-in detail drawer, booking calendar, KPI sparkline cards, and full RTL Arabic support",
    ],
    tags: ["Next.js", "TypeScript", "Tailwind"],
    emoji: "📋",
    gradient: "from-[#4f7a6a] to-[#365348]",
    demo: "https://trueform.cultivbureau.com/",
    github: "",
  },
  {
    title: "Bureau",
    description:
      "Corporate website for a digital transformation agency showcasing services and brand identity.",
    bullets: [
      "Responsive frontend optimized for desktop & mobile, improving accessibility and client engagement",
      "Complex design animations bringing digital transformation, automation, and AI solutions to life for B2B audiences",
    ],
    tags: ["React", "Tailwind", "Animation"],
    emoji: "🏢",
    gradient: "from-[#000000] to-[#ffc400]",
    demo: "https://bureau.cultiv.llc/",
    github: "",
  },
  {
    title: "DietHub",
    description: "Health & wellness web portal revamp with CMS, analytics, and SEO optimization.",
    bullets: [
      "Cross-platform responsive design delivering consistent experience across mobile & desktop",
      "SEO best practices that increased organic traffic by 320%",
      "CMS for content management and form signup tracking, plus analytics integration",
    ],
    tags: ["React", "CMS", "SEO"],
    emoji: "🥗",
    gradient: "from-[#ff5003] to-[#1a1a1a]",
    demo: "https://diethubeg.com/",
    github: "",
  },
  {
    title: "Riverty",
    description:
      "E-commerce payment method plugin integration for Magento and PrestaShop platforms.",
    bullets: [
      "Maintained and supported Riverty payment plugin in production across Magento and PrestaShop",
      "Implemented new e-commerce functionalities with task estimation and delivery",
      "Debugged compatibility issues across multiple platform versions",
    ],
    tags: ["Magento", "PrestaShop", "E-commerce"],
    emoji: "💳",
    gradient: "from-[#527a42] to-[#1e293b]",
    demo: "https://www.riverty.com/en/",
    github: "",
  },
];
